#!/usr/bin/env bash
# =============================================================================
# build_demo_data.sh — (re)generate the GLK demo dataset in demo_test/data/
# -----------------------------------------------------------------------------
# The full GLK project files are far too large for a public GitHub repository
# (GTF 547 MB, GFF 223 MB, eggNOG annotations 224 MB, expression matrix
# 1.5 GB). This script builds a small, self-contained demo subset that still
# runs the complete gwasor → Layer-1 → Layer-2 pipeline end-to-end:
#
#   * genotype  : the original addmode_Only4GLK PLINK dataset (134 samples,
#                 ~63k isoform + SV markers) — small enough to keep in full
#   * qqman     : NOT committed — generated by the demo's own GWAS run
#   * GTF       : transcript lines only, for the isoforms that matter
#                 (p ≤ 1e-5 + top-300 hits + isoforms in the expression subset)
#   * GFF       : region lines (chromosome map) + gene lines of the involved genes
#   * eggNOG    : annotation rows for the involved isoforms/genes
#   * go.tab    : kept in full (3 MB)
#   * expression: the QC-filtered TPM matrix restricted to the involved
#                 isoforms + the top-3000 most-expressed isoforms
#
# Usage:
#   PROJECT_ROOT=/path/to/the/original/04_PAV_Isoform_GWAS bash build_demo_data.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEMO_DATA="$SCRIPT_DIR/data"
PROJECT_ROOT="${PROJECT_ROOT:-}"
if [ -z "$PROJECT_ROOT" ]; then
    echo "ERROR: PROJECT_ROOT not set — point it at the original project that" >&2
    echo "       contains 02_phenotype/GLK, 05_IsoNetwork/second_lay_by_expression," >&2
    echo "       etc. (the demo data in data/ is already committed; this script" >&2
    echo "       is only needed to regenerate it)." >&2
    exit 1
fi

GLK_DIR="$PROJECT_ROOT/02_phenotype/GLK"
PHENO_DIR="$PROJECT_ROOT/02_phenotype/all_samples4GLK"
NET_DIR="$PROJECT_ROOT/05_IsoNetwork/second_lay_by_expression"
ANN_DIR="$PROJECT_ROOT/03_AnnotationFile"

mkdir -p "$DEMO_DATA"

# ---------------------------------------------------------------------------
# 1. Small files — copied verbatim
# ---------------------------------------------------------------------------
echo "=== [1/6] copying genotype / phenotype / map / go.tab ==="
cp "$GLK_DIR/addmode_Only4GLK.bed"  "$DEMO_DATA/"
cp "$GLK_DIR/addmode_Only4GLK.bim"  "$DEMO_DATA/"
cp "$GLK_DIR/addmode_Only4GLK.fam"  "$DEMO_DATA/"
cp "$GLK_DIR/addmode_Only4GLK.tfam" "$DEMO_DATA/"
cp "$PHENO_DIR/all_chlorophy_a+b"   "$DEMO_DATA/"
cp "$NET_DIR/go.tab"                "$DEMO_DATA/"
# Tab-delimited isoform genetic map (chr, isoformID, cM, pos) used by gwasor -map
cp "$PHENO_DIR/gwasout_all_Carotenoids/all_Carotenoids.map" "$DEMO_DATA/genetic_map.map"

# ---------------------------------------------------------------------------
# 2. Select the isoforms that matter (p ≤ 1e-5 ∪ top-300) + involved genes
# ---------------------------------------------------------------------------
echo "=== [2/6] selecting demo isoforms from the original GWAS qqman ==="
python3 - "$NET_DIR/chlorophyll.pheno.qqman" "$SCRIPT_DIR/selected_ids.txt" <<'PYEOF'
import re, sys
qqman, out = sys.argv[1], sys.argv[2]
RE = re.compile(r'LOC\d+|TCONS_\d+')
rows = []
with open(qqman) as f:
    for line in f:
        p = line.rstrip('\n').split('\t')
        if len(p) < 4:
            continue
        gid = RE.search(p[0]).group(0) if RE.search(p[0]) else p[0]
        rows.append((gid, float(p[3])))
# deduplicate keeping the lowest p-value per isoform/gene, then select
best = {}
for gid, pv in rows:
    if gid not in best or pv < best[gid]:
        best[gid] = pv
sig = {g for g, pv in best.items() if pv <= 1e-5}
top = [g for g, _ in sorted(best.items(), key=lambda kv: kv[1])[:300]]
sel = sorted(sig | set(top))
with open(out, 'w') as f:
    f.write('\n'.join(sel) + '\n')
print(f"  selected {len(sel)} isoforms (significant: {len(sig)}, top-300)")
PYEOF

# ---------------------------------------------------------------------------
# 3. GTF subset — transcript lines of selected isoforms + their genes
# ---------------------------------------------------------------------------
echo "=== [3/6] subsetting GTF (transcript lines only) ==="
python3 - "$ANN_DIR/pop240GTF2ref.combined.gtf" "$SCRIPT_DIR/selected_ids.txt" "$DEMO_DATA/pop240GTF2ref.combined.gtf" <<'PYEOF'
import re, sys
gtf_in, ids_file, gtf_out = sys.argv[1], sys.argv[2], sys.argv[3]
sel = set(open(ids_file).read().split())
attr_re = re.compile(r'(\S+)\s+"([^"]*)"')
keep_tids, keep_genes, out_lines = set(sel), set(), []
with open(gtf_in) as f:
    for line in f:
        if line.startswith('#'):
            continue
        p = line.rstrip('\n').split('\t')
        if len(p) < 9 or p[2] != 'transcript':
            continue
        attrs = {m.group(1): m.group(2) for m in attr_re.finditer(p[8])}
        tid, gene = attrs.get('transcript_id'), attrs.get('gene_name')
        if tid is None:
            continue
        if tid in sel:                      # first pass: collect genes of hits
            keep_genes.add(gene)
        out_lines.append((tid, gene, line))
# second pass: keep all transcripts of the involved genes
with open(gtf_out, 'w') as f:
    n = 0
    for tid, gene, line in out_lines:
        if tid in keep_tids or gene in keep_genes:
            f.write(line)
            n += 1
print(f"  wrote {n} transcript lines  ({len(keep_tids)} selected + isoforms of {len(keep_genes)} genes)")
PYEOF

# ---------------------------------------------------------------------------
# 4. Expression subset — selected isoforms + isoforms of their genes
#    + top-3000 most-expressed isoforms (from the QC-filtered matrix)
# ---------------------------------------------------------------------------
echo "=== [4/6] subsetting expression matrix ==="
python3 - "$NET_DIR/Pop_isoform_TPM_filtered.txt" "$SCRIPT_DIR/selected_ids.txt" "$DEMO_DATA/Pop_isoform_TPM_by_compareGTF.txt" <<'PYEOF'
import sys
expr_in, ids_file, expr_out = sys.argv[1], sys.argv[2], sys.argv[3]
sel = set(open(ids_file).read().split())
with open(expr_in) as f:
    header = f.readline().rstrip('\n')
    rows = []
    for line in f:
        p = line.rstrip('\n').split('\t')
        if len(p) < 2:
            continue
        key = p[0]
        if ':' in key:
            loc, tcons = key.split(':', 1)
        else:
            loc = tcons = key
        values = [float(v) for v in p[1:]] if p[1:] else []
        if tcons in sel or loc in sel:
            rows.append((key, values, True))
        else:
            rows.append((key, values, False))
# top-3000 by max TPM (excluding already-selected rows)
rows.sort(key=lambda r: max(r[1]) if r[1] else 0.0, reverse=True)
kept = []
n_sel = 0
for key, values, is_sel in rows:
    if is_sel:
        kept.append((key, values)); n_sel += 1
    elif len(kept) - n_sel < 3000:
        kept.append((key, values))
kept.sort(key=lambda kv: kv[0])
with open(expr_out, 'w') as f:
    f.write(header + '\n')
    for key, values in kept:
        f.write(key + '\t' + '\t'.join(f'{v:.6g}' for v in values) + '\n')
print(f"  wrote {len(kept)} isoforms x {len(values)} samples ({n_sel} selected + top-expressed)")
PYEOF

# ---------------------------------------------------------------------------
# 5. GFF subset — region lines (chromosome map) + gene lines of involved genes
# ---------------------------------------------------------------------------
echo "=== [5/6] subsetting GFF (region + gene lines) ==="
python3 - "$NET_DIR/Lsat_Salinas_v11_genomic.gff" "$DEMO_DATA/Pop_isoform_TPM_by_compareGTF.txt" "$DEMO_DATA/Lsat_Salinas_v11_genomic.gff" <<'PYEOF'
import re, sys
gff_in, expr_file, gff_out = sys.argv[1], sys.argv[2], sys.argv[3]
locs = set()
with open(expr_file) as f:
    next(f)
    for line in f:
        key = line.split('\t', 1)[0]
        locs.add(key.split(':', 1)[0] if ':' in key else key)
id_re = re.compile(r'ID=([^;]+)')
name_re = re.compile(r'Name=([^;]+)')
n_region = n_gene = 0
with open(gff_in) as f, open(gff_out, 'w') as o:
    for line in f:
        if line.startswith('#') or not line.strip():
            continue
        p = line.rstrip('\n').split('\t')
        if len(p) < 9:
            continue
        if p[2] == 'region':
            o.write(line); n_region += 1
        elif p[2] == 'gene':
            m = id_re.search(p[8])
            gid = m.group(1).replace('gene-', '') if m else ''
            if not gid.startswith('LOC'):
                m = name_re.search(p[8])
                gid = m.group(1) if m else gid
            if gid in locs:
                o.write(line); n_gene += 1
print(f"  wrote {n_region} region lines + {n_gene} gene lines")
PYEOF

# ---------------------------------------------------------------------------
# 6. eggNOG annotation subset — header + rows of involved isoforms/genes
# ---------------------------------------------------------------------------
echo "=== [6/6] subsetting eggNOG annotations ==="
python3 - "$NET_DIR/isoform_and_gene.emapper.annotations" "$SCRIPT_DIR/selected_ids.txt" "$DEMO_DATA/Pop_isoform_TPM_by_compareGTF.txt" "$DEMO_DATA/isoform_and_gene.emapper.annotations" <<'PYEOF'
import sys
anno_in, ids_file, expr_file, anno_out = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
keep = set(open(ids_file).read().split())
with open(expr_file) as f:
    next(f)
    for line in f:
        key = line.split('\t', 1)[0]
        keep.add(key)
        keep.add(key.split(':', 1)[0] if ':' in key else key)
n = 0
with open(anno_in) as f, open(anno_out, 'w') as o:
    for line in f:
        if line.startswith('##'):
            o.write(line)
            continue
        if line.startswith('#'):            # header line
            o.write(line)
            continue
        qid = line.split('\t', 1)[0]
        if qid in keep:
            o.write(line); n += 1
print(f"  wrote header + {n} annotation rows")
PYEOF

echo ""
echo "=== demo data ready in $DEMO_DATA ==="
rm -f "$SCRIPT_DIR/selected_ids.txt"    # build intermediate
du -sh "$DEMO_DATA"
ls -la "$DEMO_DATA"
